import { useState } from "react";
import {
  Box,
  Button,
  Card,
  CardActions,
  CardContent,
  CardHeader,
  Chip,
  Divider,
  Grid,
  Stack,
  Typography,
} from "@mui/material";
import type { ArsenalChannelCategoryMeta } from "../types/apiContracts";

type UsageCount = {
  label: string;
  count: number;
};

type UsagePersona = {
  id: string;
  label?: string | null;
  count: number;
};

type UsageAccount = {
  id: string;
  name?: string | null;
  industry?: string | null;
  revenue_range?: string | null;
  employee_range?: string | null;
  geography?: string | null;
  funding_stage?: string | null;
};

type AssetUsage = {
  total_engagements: number;
  accounts?: UsageAccount[];
  industries?: UsageCount[];
  regions?: UsageCount[];
  sizes?: UsageCount[];
  personas?: UsagePersona[];
  concerns?: UsageCount[];
  stages?: Array<{ code?: string | null; label: string; count: number }>;
  segments?: UsageCount[];
};

type Asset = {
  id: string;
  name: string;
  slug?: string;
  category?: string | null;
  content_type?: string | null;
  time_to_consume?: string | null;
  depth?: string | null;
  metadata_complete?: boolean;
  description?: string | null;
  notes?: string | null;
  call_stage?: string | null;
  impacts?: Array<{
    persona_id: string;
    persona_label?: string | null;
    belief_transition_id?: string | null;
    impact_strength?: number | null;
    evidence_count?: number | null;
  }>;
  target_personas?: string[] | null;
  target_account_segments?: string[] | null;
  target_belief_stages?: string[] | null;
  target_concerns?: string[] | null;
  usage?: AssetUsage;
  typical_channels?: Array<{ id: string; label?: string | null }> | null;
  approval_status?: string | null;
  derived_metadata?: Record<string, any> | null;
  auto_classification_confidence?: number | null;
  primary_channel?: { id: string; name?: string | null } | null;
  activity_labels?: string[] | null;
  asset_category_meta?: {
    label?: string;
    activity_stages?: string[];
  };
  asset_activity_summary?: string;
  org_conversion_maturity?: {
    code?: string;
    label?: string;
  };
  asset_channel_stats?: Array<{
    channel_slug: string;
    channel_label: string;
    engagements: number;
    personas?: Array<{ id: string; count: number }>;
    stages?: Array<{ code: string; count: number }>;
  }>;
};

type ChannelLookup = {
  id: string;
  name?: string;
  slug?: string;
  channel_category_meta?: ArsenalChannelCategoryMeta;
};

interface AssetsLibraryProps {
  assets: Asset[];
  onEdit: (asset: Asset) => void;
  onApprove: (asset: Asset) => void;
  channelLookup: Record<string, ChannelLookup>;
}

const toTitleCase = (value: string) =>
  value
    .replace(/[_\s]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .split(" ")
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");

const formatMetadataLabel = (value?: string | null) => {
  if (!value) return "";
  return toTitleCase(value);
};

const formatDisplayTitle = (asset: Asset) => {
  const derived = asset.derived_metadata?.asset_name?.label;
  if (derived) {
    return derived;
  }
  const match = asset.name?.match(/['"]([^'"]+)['"]/);
  if (match?.[1]) {
    return match[1];
  }
  return asset.name;
};

const buildAutoGeneratedText = (asset: Asset, key: string) => {
  const field = asset.derived_metadata?.[key];
  if (!field || typeof field !== "object") {
    return null;
  }
  const label = field.label;
  if (!label) return null;
  return label;
};

const summarySlice = (items?: string[] | null, limit = 3) => {
  if (!items || !items.length) return [];
  const unique = Array.from(new Set(items));
  return unique.slice(0, limit);
};

const AssetsLibrary = ({
  assets,
  onEdit,
  onApprove,
  channelLookup,
}: AssetsLibraryProps) => {
  const [expandedAssetId, setExpandedAssetId] = useState<string | null>(null);
  if (!assets.length) {
    return (
      <Grid container spacing={2}>
        <Grid size={12}>
          <Typography color="text.secondary">No assets found.</Typography>
        </Grid>
      </Grid>
    );
  }

  const renderAssetCard = (asset: Asset) => {
    const metadataComplete = Boolean(asset.metadata_complete);
    const needsApproval = (asset.approval_status || "pending") !== "approved";
    const evidenceCount = asset.impacts?.reduce(
      (sum, impact) => sum + (impact.evidence_count || 0),
      0
    );
    const positiveStrength =
      asset.impacts && asset.impacts.length
        ? asset.impacts.reduce((sum, impact) => sum + (impact.impact_strength || 0), 0) /
          asset.impacts.length
        : null;
    const displayTitle = formatDisplayTitle(asset);
    const assetCategoryLabel =
      asset.asset_category_meta?.label || formatMetadataLabel(asset.category) || "Category missing";
    const activityLabel =
      asset.asset_activity_summary ||
      asset.derived_metadata?.activity?.label ||
      "No action";
    const categoryStages = asset.asset_category_meta?.activity_stages || [];
    const targetPersonas = asset.target_personas ?? [];
    const targetSegments = asset.target_account_segments ?? [];
    const targetStages = asset.target_belief_stages ?? [];
    const targetConcerns = asset.target_concerns ?? [];
    const channelCategories = (asset.typical_channels ?? [])
      .map((entry) => channelLookup[entry.id])
      .filter((channel): channel is ChannelLookup => Boolean(channel))
      .map((channel) => channel.channel_category_meta)
      .filter((meta): meta is ArsenalChannelCategoryMeta => Boolean(meta));
    const uniqueChannelCategories = Array.from(
      new Map(
        channelCategories.map((meta) => [meta.key, meta])
      ).values()
    );
    const hasUsage = Boolean((asset.usage?.total_engagements ?? 0) > 0);
    const bestChannels = (asset.asset_channel_stats || []).slice(0, 3);

    return (
      <Grid key={asset.id} item xs={12} md={6}>
        <Card sx={{ height: "100%", display: "flex", flexDirection: "column" }} variant="outlined">
          <CardHeader
            title={
              <Stack direction="row" spacing={1} alignItems="center" flexWrap="wrap">
                <Typography variant="h6">{displayTitle}</Typography>
                <Chip
                  size="small"
                  color={metadataComplete ? "success" : "warning"}
                  variant={metadataComplete ? "outlined" : "filled"}
                  label={metadataComplete ? "Metadata complete" : "Needs metadata"}
                />
                {needsApproval && (
                  <Chip size="small" color="warning" label="Needs approval" />
                )}
              </Stack>
            }
            subheader={
              <Stack direction="row" spacing={1} alignItems="center" flexWrap="wrap">
                <Chip label={`Asset category: ${assetCategoryLabel}`} size="small" />
                <Chip label={`Activity: ${activityLabel}`} size="small" />
              </Stack>
            }
            sx={{ pb: 0 }}
          />
          <CardContent sx={{ flexGrow: 1, display: "flex", flexDirection: "column", gap: 1 }}>
            <Stack spacing={1}>
              <Stack direction="row" spacing={0.5} flexWrap="wrap">
                {asset.time_to_consume && (
                  <Chip label={`Time: ${formatMetadataLabel(asset.time_to_consume)}`} size="small" />
                )}
                {asset.depth && (
                  <Chip label={`Depth: ${formatMetadataLabel(asset.depth)}`} size="small" />
                )}
                {asset.call_stage && (
                  <Chip
                    label={`Stage: ${formatMetadataLabel(asset.call_stage)}`}
                    size="small"
                  />
                )}
                {asset.org_conversion_maturity?.label && (
                  <Chip
                    label={`Org maturity: ${formatMetadataLabel(
                      asset.org_conversion_maturity.label
                    )}`}
                    size="small"
                    color="info"
                  />
                )}
              </Stack>
              {categoryStages.length > 0 && (
                <Box>
                  <Typography variant="caption">Asset category activity stages</Typography>
                  <Stack direction="row" spacing={0.5} flexWrap="wrap" sx={{ mt: 0.5 }}>
                    {categoryStages.map((stage) => (
                      <Chip key={stage} size="small" variant="outlined" label={stage} />
                    ))}
                  </Stack>
                </Box>
              )}
              {targetPersonas.length > 0 && (
                <Box>
                  <Typography variant="caption">Target personas</Typography>
                  <Stack direction="row" spacing={0.5} flexWrap="wrap" sx={{ mt: 0.5 }}>
                    {summarySlice(targetPersonas).map((persona) => (
                      <Chip key={persona} size="small" color="info" variant="outlined" label={persona} />
                    ))}
                  </Stack>
                </Box>
              )}
              {targetSegments.length > 0 && (
                <Box>
                  <Typography variant="caption">Target segments</Typography>
                  <Stack direction="row" spacing={0.5} flexWrap="wrap" sx={{ mt: 0.5 }}>
                    {summarySlice(targetSegments).map((segment) => (
                      <Chip key={segment} size="small" variant="outlined" label={segment} />
                    ))}
                  </Stack>
                </Box>
              )}
              {targetStages.length > 0 && (
                <Box>
                  <Typography variant="caption">Target beliefs</Typography>
                  <Stack direction="row" spacing={0.5} flexWrap="wrap" sx={{ mt: 0.5 }}>
                    {summarySlice(targetStages).map((stage) => (
                      <Chip key={stage} size="small" variant="outlined" label={stage} />
                    ))}
                  </Stack>
                </Box>
              )}
              {targetConcerns.length > 0 && (
                <Box>
                  <Typography variant="caption">Key concerns</Typography>
                  <Stack direction="row" spacing={0.5} flexWrap="wrap" sx={{ mt: 0.5 }}>
                    {summarySlice(targetConcerns).map((concern) => (
                      <Chip key={concern} size="small" variant="outlined" label={concern} />
                    ))}
                  </Stack>
                </Box>
              )}
              {uniqueChannelCategories.length > 0 && (
                <Box>
                  <Typography variant="caption">Channel categories</Typography>
                  <Stack direction="row" spacing={0.5} flexWrap="wrap" sx={{ mt: 0.5 }}>
                    {uniqueChannelCategories.map((category) => (
                      <Chip
                        key={category.key}
                        size="small"
                        variant="outlined"
                        label={
                          `${category.label || formatMetadataLabel(category.name)}`
                        }
                      />
                    ))}
                  </Stack>
                </Box>
              )}
            </Stack>

            {needsApproval && asset.derived_metadata && (
              <Box
                sx={{
                  borderRadius: 1,
                  border: 1,
                  borderColor: "warning.light",
                  p: 1,
                }}
              >
                <Typography variant="caption" color="warning.main">
                  Auto-generated
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  Suggested asset: {buildAutoGeneratedText(asset, "asset_name") || "—"}
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  Suggested channel: {buildAutoGeneratedText(asset, "channel") || "—"}
                </Typography>
                {typeof asset.auto_classification_confidence === "number" && (
                  <Typography variant="caption" color="text.secondary">
                    Confidence {(asset.auto_classification_confidence * 100).toFixed(0)}%
                  </Typography>
                )}
              </Box>
            )}

            {asset.notes && (
              <Typography variant="body2" color="text.secondary">
                Notes: {asset.notes}
              </Typography>
            )}
            {asset.primary_channel && (
              <Typography variant="body2" color="text.secondary">
                Primary channel: {asset.primary_channel.name}
              </Typography>
            )}

            {hasUsage && (
              <Box>
                <Typography variant="caption">Usage evidence</Typography>
                <Stack direction="row" spacing={1} flexWrap="wrap" sx={{ mt: 0.5 }}>
                  {asset.usage?.stages?.slice(0, 2).map((stage) => (
                    <Chip
                      key={`${asset.id}-${stage.label}`}
                      size="small"
                      label={`${stage.label} (${stage.count})`}
                    />
                  ))}
                </Stack>
              </Box>
              )}
              {bestChannels.length > 0 && (
                <Box>
                  <Typography variant="caption">Best invitation channels</Typography>
                  <Stack direction="row" spacing={0.5} flexWrap="wrap" sx={{ mt: 0.5 }}>
                    {bestChannels.map((channel) => (
                      <Chip
                        key={`${asset.id}-${channel.channel_slug}`}
                        size="small"
                        variant="outlined"
                        label={`${channel.channel_label} (${channel.engagements})`}
                      />
                    ))}
                  </Stack>
                </Box>
              )}
          </CardContent>
          <Divider />
          <CardActions sx={{ justifyContent: "space-between" }}>
            <Stack direction="row" spacing={1}>
              <Button size="small" onClick={() => onEdit(asset)}>
                Edit
              </Button>
              <Button
                size="small"
                variant="contained"
                onClick={() => onApprove(asset)}
                disabled={!needsApproval}
              >
                Approve
              </Button>
            </Stack>
            <Button
              size="small"
              onClick={() =>
                setExpandedAssetId((prev) => (prev === asset.id ? null : asset.id))
              }
            >
              {expandedAssetId === asset.id ? "Collapse" : "Details"}
            </Button>
          </CardActions>
        </Card>
      </Grid>
    );
  };

  return (
    <Grid container spacing={2}>
      {assets.map((asset) => renderAssetCard(asset))}
    </Grid>
  );
};

export default AssetsLibrary;
